export type Category = "museum" | "coffee" | "dining" | "beach" | "hotel" | "shopping"

export interface Experience {
  id: string
  name: string
  category: Category
  cuisine?: string
  description: string
  shortDescription: string
  duration: string
  timeRange: string
  tags: string[]
  indoor: boolean
  ticketRequired: boolean
  walkingDistance: string
  image: string
  whyChosen: string
  tips: string[]
  lat: number
  lng: number
}

export interface DayItinerary {
  day: number
  date: string
  experiences: Experience[]
}

// ─── MUSEUMS ────────────────────────────────────────────────────────────────
export const museums: Experience[] = [
  {
    id: "louvre-abu-dhabi",
    name: "Louvre Abu Dhabi",
    category: "museum",
    description: "Explore the universal museum designed by Jean Nouvel, featuring a stunning dome that creates a 'rain of light' effect. The collection spans civilizations and cultures from prehistory to contemporary works.",
    shortDescription: "Universal museum by Jean Nouvel with a breathtaking rain of light dome.",
    duration: "2.5 hrs",
    timeRange: "10:00 - 12:30",
    tags: ["Art", "Indoor", "Architecture"],
    indoor: true,
    ticketRequired: true,
    walkingDistance: "5 min from drop-off",
    image: "/images/louvre.jpg",
    whyChosen: "Based on your interest in art and architecture, the Louvre Abu Dhabi is a must-see landmark of Saadiyat Island.",
    tips: ["Visit early morning for fewer crowds", "Smart casual dress code recommended", "Photography allowed without flash", "Audio guide available in multiple languages"],
    lat: 24.5338,
    lng: 54.3983,
  },
  {
    id: "abrahamic-family-house",
    name: "The Abrahamic Family House",
    category: "museum",
    description: "A landmark complex comprising a mosque, church, and synagogue, symbolizing coexistence and dialogue among the three Abrahamic faiths. Designed by Sir David Adjaye.",
    shortDescription: "Iconic interfaith complex by Sir David Adjaye symbolizing coexistence.",
    duration: "1.5 hrs",
    timeRange: "09:00 - 10:30",
    tags: ["Spiritual", "Architecture", "Indoor"],
    indoor: true,
    ticketRequired: true,
    walkingDistance: "8 min from hotel",
    image: "/images/abrahamic.jpg",
    whyChosen: "A deeply meaningful architectural and spiritual experience aligned with your interest in reflection.",
    tips: ["Modest dress required for all three houses of worship", "Guided tours available", "Morning light is best for photography", "Allow time for quiet reflection"],
    lat: 24.5182,
    lng: 54.4063,
  },
  {
    id: "manarat-al-saadiyat",
    name: "Manarat Al Saadiyat",
    category: "museum",
    description: "A vibrant arts and culture center hosting rotating exhibitions, workshops, and community events. The gallery spaces showcase contemporary art from the UAE and around the world.",
    shortDescription: "Contemporary arts center with rotating exhibitions and cultural events.",
    duration: "1.5 hrs",
    timeRange: "13:30 - 15:00",
    tags: ["Art", "Indoor", "Culture"],
    indoor: true,
    ticketRequired: false,
    walkingDistance: "10 min walk",
    image: "/images/manarat.jpg",
    whyChosen: "A relaxed gallery experience that complements the Louvre visit, perfect for your balanced pace.",
    tips: ["Check current exhibitions online before visiting", "Gift shop has unique local art pieces", "Cafe on-site for a light break"],
    lat: 24.5401,
    lng: 54.4108,
  },
  {
    id: "teamlab-phenomena",
    name: "teamLab Phenomena Abu Dhabi",
    category: "museum",
    description: "An immersive digital art museum by the renowned Japanese art collective teamLab, offering a transcendent experience where visitors become part of the artwork in vast, borderless spaces.",
    shortDescription: "Immersive digital art museum by the Japanese collective teamLab.",
    duration: "2 hrs",
    timeRange: "14:00 - 16:00",
    tags: ["Art", "Indoor", "Immersive"],
    indoor: true,
    ticketRequired: true,
    walkingDistance: "6 min from Louvre",
    image: "/images/teamlab.jpg",
    whyChosen: "A cutting-edge art experience that's unlike anything else, perfect for art enthusiasts.",
    tips: ["Wear comfortable shoes for walking through installations", "Allow at least 2 hours for the full experience", "Photography and video encouraged", "Some rooms are dark; take care with young children"],
    lat: 24.536,
    lng: 54.401,
  },
  {
    id: "zayed-national-museum",
    name: "Zayed National Museum",
    category: "museum",
    description: "Dedicated to the life and legacy of the UAE's founding father, Sheikh Zayed bin Sultan Al Nahyan. Designed by Foster + Partners with wing-like steel structures inspired by falcon feathers.",
    shortDescription: "Museum honoring the UAE's founding father, designed by Foster + Partners.",
    duration: "2 hrs",
    timeRange: "10:00 - 12:00",
    tags: ["History", "Architecture", "Indoor"],
    indoor: true,
    ticketRequired: true,
    walkingDistance: "10 min from Louvre",
    image: "/images/zayed-national-museum.jpg",
    whyChosen: "A profound tribute to UAE heritage with world-class architecture.",
    tips: ["Don't miss the wing-inspired exterior at sunset", "Interactive displays throughout", "Combined tickets available with other museums"],
    lat: 24.5345,
    lng: 54.3965,
  },
  {
    id: "natural-history-museum",
    name: "Natural History Museum Abu Dhabi",
    category: "museum",
    description: "Discover 13.8 billion years of history through interactive exhibits, rare specimens, and cutting-edge technology. Home to 'Stan,' one of the most complete T. Rex fossils ever found.",
    shortDescription: "Explore 13.8 billion years of history with rare specimens and 'Stan' the T. Rex.",
    duration: "2 hrs",
    timeRange: "10:30 - 12:30",
    tags: ["Indoor", "Culture", "Architecture"],
    indoor: true,
    ticketRequired: true,
    walkingDistance: "7 min from Louvre",
    image: "/images/natural-history.jpg",
    whyChosen: "An awe-inspiring journey through Earth's history, great for curious minds.",
    tips: ["Don't miss the Stan the T. Rex exhibit", "Interactive displays are great for all ages", "The gift shop has unique fossil replicas"],
    lat: 24.535,
    lng: 54.403,
  },
  {
    id: "bassam-freiha-art-foundation",
    name: "Bassam Freiha Art Foundation",
    category: "museum",
    description: "A contemporary art foundation showcasing international and regional artists in a beautifully designed gallery space. Features rotating exhibitions and permanent collections.",
    shortDescription: "Contemporary art foundation with international and regional exhibitions.",
    duration: "1 hr",
    timeRange: "11:00 - 12:00",
    tags: ["Art", "Indoor", "Culture"],
    indoor: true,
    ticketRequired: false,
    walkingDistance: "5 min from Manarat",
    image: "/images/bassam-freiha.jpg",
    whyChosen: "An intimate gallery experience showcasing cutting-edge contemporary art.",
    tips: ["Check for artist talks and events", "Smaller venue, usually less crowded", "Rotating exhibitions change quarterly"],
    lat: 24.5395,
    lng: 54.4115,
  },
  {
    id: "mamsha-al-saadiyat",
    name: "Mamsha Al Saadiyat",
    category: "museum",
    description: "A vibrant beachfront promenade and residential community featuring public art installations, boutique restaurants, and stunning views of the Arabian Gulf.",
    shortDescription: "Beachfront promenade with public art, dining, and Gulf views.",
    duration: "1.5 hrs",
    timeRange: "17:00 - 18:30",
    tags: ["Outdoor", "Art", "Shopping"],
    indoor: false,
    ticketRequired: false,
    walkingDistance: "On the waterfront",
    image: "/images/mamsha.jpg",
    whyChosen: "A beautiful sunset stroll combining art, dining, and ocean views.",
    tips: ["Walk along the beachfront for the best views", "Many restaurants line the promenade", "Great spot for sunset photography"],
    lat: 24.5472,
    lng: 54.4325,
  },
]

// ─── COFFEE & CAFES ─────────────────────────────────────────────────────────
export const coffeeShops: Experience[] = [
  {
    id: "mysk-bakery",
    name: "Mysk",
    category: "coffee",
    cuisine: "Bakery",
    description: "A charming bakery offering freshly baked pastries, artisan breads, and specialty coffee. The perfect morning stop with a warm, inviting atmosphere.",
    shortDescription: "Artisan bakery with freshly baked pastries and specialty coffee.",
    duration: "30 min",
    timeRange: "08:00 - 08:30",
    tags: ["Coffee", "Bakery", "Breakfast"],
    indoor: true,
    ticketRequired: false,
    walkingDistance: "Varies",
    image: "/images/cafe-default.jpg",
    whyChosen: "A delightful start to the morning with fresh pastries before exploring.",
    tips: ["Try the croissants", "Great for a quick breakfast stop"],
    lat: 24.5405,
    lng: 54.4120,
  },
  {
    id: "cafe-artea",
    name: "Cafe Artea",
    category: "coffee",
    cuisine: "Art-themed Coffee",
    description: "An art-themed cafe that blends creative aesthetics with specialty coffee. The decor features rotating local artwork and the menu offers unique tea and coffee blends.",
    shortDescription: "Art-themed cafe with specialty coffee and rotating local artwork.",
    duration: "45 min",
    timeRange: "09:00 - 09:45",
    tags: ["Coffee", "Art", "Indoor"],
    indoor: true,
    ticketRequired: false,
    walkingDistance: "On Saadiyat Island",
    image: "/images/cafe-default.jpg",
    whyChosen: "Combines your love of art with a relaxing coffee break.",
    tips: ["Ask about the featured artist", "Try the signature art-inspired drinks"],
    lat: 24.5410,
    lng: 54.4130,
  },
  {
    id: "coffee-architecture",
    name: "Coffee Architecture",
    category: "coffee",
    cuisine: "Specialty Coffee",
    description: "A specialty coffee roaster with a modern, architecturally inspired interior. Known for single-origin brews and precise pour-over techniques.",
    shortDescription: "Specialty coffee roaster with single-origin brews and modern design.",
    duration: "30 min",
    timeRange: "08:30 - 09:00",
    tags: ["Coffee", "Specialty", "Indoor"],
    indoor: true,
    ticketRequired: false,
    walkingDistance: "In Abu Dhabi",
    image: "/images/cafe-default.jpg",
    whyChosen: "For the discerning coffee lover who appreciates craft roasting.",
    tips: ["Try the pour-over selection", "Ask about the daily single-origin"],
    lat: 24.5390,
    lng: 54.4095,
  },
  {
    id: "nayzak-cafe",
    name: "Nayzak Cafe",
    category: "coffee",
    cuisine: "General",
    description: "A casual and welcoming cafe offering a range of coffees, teas, and light bites in a comfortable setting.",
    shortDescription: "Casual cafe with coffee, tea, and light bites.",
    duration: "30 min",
    timeRange: "09:00 - 09:30",
    tags: ["Coffee", "Casual", "Indoor"],
    indoor: true,
    ticketRequired: false,
    walkingDistance: "On Saadiyat Island",
    image: "/images/cafe-default.jpg",
    whyChosen: "A relaxing pit-stop between museum visits.",
    tips: ["Good variety of hot and cold drinks", "Friendly staff"],
    lat: 24.5415,
    lng: 54.4105,
  },
  {
    id: "cabana-9",
    name: "Cabana 9 @ Saadiyat Beach Club",
    category: "coffee",
    cuisine: "Cafe",
    description: "A beachside cafe at the Saadiyat Beach Club offering refreshing drinks, light bites, and stunning ocean views from cabana seating.",
    shortDescription: "Beachside cafe with ocean views and refreshing drinks.",
    duration: "45 min",
    timeRange: "11:00 - 11:45",
    tags: ["Coffee", "Beach", "Outdoor"],
    indoor: false,
    ticketRequired: false,
    walkingDistance: "At Saadiyat Beach Club",
    image: "/images/saadiyat-beach-club.jpg",
    whyChosen: "Coffee with a view -- the perfect beach break.",
    tips: ["Best enjoyed with toes in the sand", "Pair with a fresh juice"],
    lat: 24.5465,
    lng: 54.4335,
  },
  {
    id: "aptitude-cafe",
    name: "Aptitude Cafe & Eatery",
    category: "coffee",
    cuisine: "General",
    description: "A popular neighborhood cafe known for hearty breakfasts, smooth coffees, and a warm community atmosphere.",
    shortDescription: "Community cafe with hearty breakfasts and smooth coffee.",
    duration: "45 min",
    timeRange: "08:00 - 08:45",
    tags: ["Coffee", "Breakfast", "Indoor"],
    indoor: true,
    ticketRequired: false,
    walkingDistance: "Near Saadiyat",
    image: "/images/cafe-default.jpg",
    whyChosen: "Great for a filling breakfast to fuel your day of exploring.",
    tips: ["Try the eggs Benedict", "Popular on weekends -- arrive early"],
    lat: 24.5388,
    lng: 54.4100,
  },
  {
    id: "blacksmith-coffee",
    name: "Blacksmith Coffee Company",
    category: "coffee",
    cuisine: "General",
    description: "A craft coffee shop with industrial-chic vibes, known for expertly pulled espresso shots and a rotating selection of specialty beans.",
    shortDescription: "Craft coffee shop with industrial vibes and expert espresso.",
    duration: "30 min",
    timeRange: "09:00 - 09:30",
    tags: ["Coffee", "Specialty", "Indoor"],
    indoor: true,
    ticketRequired: false,
    walkingDistance: "Near Saadiyat",
    image: "/images/cafe-default.jpg",
    whyChosen: "Excellent espresso to power through a day of cultural exploration.",
    tips: ["Ask for the daily special", "Great flat whites"],
    lat: 24.5392,
    lng: 54.4088,
  },
  {
    id: "baytooty-bakery",
    name: "Baytooty Gourmet Bakery",
    category: "coffee",
    cuisine: "Lebanese",
    description: "A Lebanese bakery offering traditional manakish, freshly baked kaak, and Middle Eastern pastries alongside strong Arabic coffee.",
    shortDescription: "Lebanese bakery with manakish, kaak, and Arabic coffee.",
    duration: "30 min",
    timeRange: "08:00 - 08:30",
    tags: ["Coffee", "Lebanese", "Bakery"],
    indoor: true,
    ticketRequired: false,
    walkingDistance: "Near Saadiyat",
    image: "/images/cafe-default.jpg",
    whyChosen: "Authentic Lebanese flavors for a morning with local character.",
    tips: ["Must-try: zaatar manakish", "Fresh juices also excellent"],
    lat: 24.5400,
    lng: 54.4112,
  },
  {
    id: "museum-cafe-louvre",
    name: "Museum Cafe Louvre",
    category: "coffee",
    cuisine: "General",
    description: "Located within the Louvre Abu Dhabi complex, this cafe offers light refreshments and specialty coffees with views of the museum's striking architecture.",
    shortDescription: "Cafe inside Louvre Abu Dhabi with architectural views.",
    duration: "30 min",
    timeRange: "12:30 - 13:00",
    tags: ["Coffee", "Museum", "Indoor"],
    indoor: true,
    ticketRequired: false,
    walkingDistance: "Inside Louvre Abu Dhabi",
    image: "/images/louvre.jpg",
    whyChosen: "A natural mid-museum break under the iconic dome.",
    tips: ["No museum ticket needed for the cafe area", "Great photo spot"],
    lat: 24.5340,
    lng: 54.3985,
  },
  {
    id: "raclette-cafe",
    name: "Raclette Cafe",
    category: "coffee",
    cuisine: "French",
    description: "A French-inspired cafe serving artisan coffees, delicate pastries, and light French fare in an elegant setting.",
    shortDescription: "French-inspired cafe with artisan coffee and delicate pastries.",
    duration: "30 min",
    timeRange: "15:00 - 15:30",
    tags: ["Coffee", "French", "Indoor"],
    indoor: true,
    ticketRequired: false,
    walkingDistance: "On Saadiyat Island",
    image: "/images/cafe-default.jpg",
    whyChosen: "An afternoon pick-me-up with French charm.",
    tips: ["Try the croque monsieur", "Excellent tea selection too"],
    lat: 24.5408,
    lng: 54.4118,
  },
  {
    id: "al-ghaf-cafe",
    name: "Al Ghaf Cafe",
    category: "coffee",
    cuisine: "General",
    description: "Located at the Zayed National Museum, this cafe is named after the UAE's national tree and offers locally inspired drinks and snacks.",
    shortDescription: "ZNM cafe named after the UAE's national tree with local flavors.",
    duration: "30 min",
    timeRange: "12:00 - 12:30",
    tags: ["Coffee", "Local", "Museum"],
    indoor: true,
    ticketRequired: false,
    walkingDistance: "At Zayed National Museum",
    image: "/images/zayed-national-museum.jpg",
    whyChosen: "A culturally inspired coffee break right at the museum.",
    tips: ["Try the date-infused drinks", "Great post-museum stop"],
    lat: 24.5346,
    lng: 54.3968,
  },
  {
    id: "mara-cafe",
    name: "MARA Cafe",
    category: "coffee",
    cuisine: "General",
    description: "A serene cafe at the Abrahamic Family House offering coffees, teas, and light meals in a peaceful garden setting that reflects the site's theme of coexistence.",
    shortDescription: "Peaceful cafe at the Abrahamic Family House.",
    duration: "30 min",
    timeRange: "10:30 - 11:00",
    tags: ["Coffee", "Spiritual", "Indoor"],
    indoor: true,
    ticketRequired: false,
    walkingDistance: "At Abrahamic Family House",
    image: "/images/abrahamic.jpg",
    whyChosen: "A reflective pause after visiting the interfaith complex.",
    tips: ["Beautiful garden seating", "Calm atmosphere for journaling"],
    lat: 24.5184,
    lng: 54.4065,
  },
  {
    id: "anko-abu-dhabi",
    name: "Anko Abu Dhabi",
    category: "coffee",
    cuisine: "Japanese",
    description: "A Japanese-inspired cafe at teamLab Phenomena offering matcha, specialty Japanese teas, and wagashi-style sweets.",
    shortDescription: "Japanese cafe at teamLab with matcha and wagashi sweets.",
    duration: "30 min",
    timeRange: "16:00 - 16:30",
    tags: ["Coffee", "Japanese", "Indoor"],
    indoor: true,
    ticketRequired: false,
    walkingDistance: "At teamLab Phenomena",
    image: "/images/teamlab.jpg",
    whyChosen: "A zen way to wind down after the immersive art experience.",
    tips: ["Try the ceremonial-grade matcha", "Wagashi are handmade daily"],
    lat: 24.5362,
    lng: 54.4012,
  },
  {
    id: "mill-cafe",
    name: "MILL Cafe",
    category: "coffee",
    cuisine: "General",
    description: "A trendy third-wave coffee shop focused on ethically sourced beans, light-roast profiles, and clean aesthetic design.",
    shortDescription: "Third-wave coffee shop with ethically sourced beans.",
    duration: "30 min",
    timeRange: "09:00 - 09:30",
    tags: ["Coffee", "Specialty", "Indoor"],
    indoor: true,
    ticketRequired: false,
    walkingDistance: "Near Saadiyat",
    image: "/images/cafe-default.jpg",
    whyChosen: "Top-tier specialty coffee for purists.",
    tips: ["Ask about the origin of the day", "Clean minimalist space"],
    lat: 24.5395,
    lng: 54.4098,
  },
]

// ─── DINING ─────────────────────────────────────────────────────────────────
export const restaurants: Experience[] = [
  {
    id: "fouquets-abu-dhabi",
    name: "Fouquet's Abu Dhabi",
    category: "dining",
    cuisine: "French",
    description: "An elegant French brasserie located at the Louvre Abu Dhabi offering refined dining with views of the museum's architecture. Enjoy classic French cuisine with an Arabian twist.",
    shortDescription: "Refined French brasserie with stunning museum-side views.",
    duration: "1.5 hrs",
    timeRange: "12:30 - 14:00",
    tags: ["Food", "Indoor", "Premium"],
    indoor: true,
    ticketRequired: false,
    walkingDistance: "2 min from Louvre",
    image: "/images/fouquets.jpg",
    whyChosen: "A premium dining experience steps from the Louvre, perfect for your interest in food.",
    tips: ["Reservations recommended for lunch", "Terrace seating has the best views"],
    lat: 24.534,
    lng: 54.399,
  },
  {
    id: "hawksbill",
    name: "Hawksbill Restaurant",
    category: "dining",
    cuisine: "Mediterranean",
    description: "A beachfront Mediterranean restaurant named after the endangered hawksbill turtles that nest on Saadiyat shores. Fresh seafood and seasonal ingredients.",
    shortDescription: "Beachfront Mediterranean with fresh seafood and turtle-inspired charm.",
    duration: "1.5 hrs",
    timeRange: "13:00 - 14:30",
    tags: ["Food", "Seafood", "Outdoor"],
    indoor: false,
    ticketRequired: false,
    walkingDistance: "At the beach",
    image: "/images/dining-default.jpg",
    whyChosen: "Fresh seafood with ocean views and a conservation story.",
    tips: ["Try the catch of the day", "Sunset dinner is magical"],
    lat: 24.5460,
    lng: 54.4330,
  },
  {
    id: "toto-saadiyat",
    name: "TOTO Saadiyat Island",
    category: "dining",
    cuisine: "Italian",
    description: "Authentic Italian trattoria serving handmade pastas, wood-fired pizzas, and classic Italian desserts in a warm, lively setting.",
    shortDescription: "Authentic Italian trattoria with handmade pasta and wood-fired pizzas.",
    duration: "1.5 hrs",
    timeRange: "19:00 - 20:30",
    tags: ["Food", "Italian", "Indoor"],
    indoor: true,
    ticketRequired: false,
    walkingDistance: "At Mamsha Al Saadiyat",
    image: "/images/dining-default.jpg",
    whyChosen: "Heartwarming Italian fare for a satisfying evening meal.",
    tips: ["Handmade pasta is the highlight", "Reservations recommended for dinner"],
    lat: 24.5470,
    lng: 54.4320,
  },
  {
    id: "ting-irie",
    name: "Ting Irie Saadiyat Island",
    category: "dining",
    cuisine: "Jamaican / Caribbean",
    description: "A vibrant Jamaican and Caribbean restaurant bringing island flavors to Saadiyat with jerk chicken, rum cocktails, and reggae vibes.",
    shortDescription: "Vibrant Jamaican restaurant with jerk chicken and island vibes.",
    duration: "1 hr",
    timeRange: "13:00 - 14:00",
    tags: ["Food", "Caribbean", "Outdoor"],
    indoor: false,
    ticketRequired: false,
    walkingDistance: "At Mamsha Al Saadiyat",
    image: "/images/dining-default.jpg",
    whyChosen: "Something different -- Caribbean flavors in the heart of Abu Dhabi.",
    tips: ["The jerk chicken is a must", "Great cocktail menu"],
    lat: 24.5468,
    lng: 54.4318,
  },
  {
    id: "niri-restaurant",
    name: "NIRI Restaurant & Bar",
    category: "dining",
    cuisine: "Japanese",
    description: "A refined Japanese restaurant offering sushi, sashimi, and izakaya-style small plates in a sleek contemporary setting.",
    shortDescription: "Refined Japanese restaurant with sushi and izakaya-style dining.",
    duration: "1.5 hrs",
    timeRange: "19:30 - 21:00",
    tags: ["Food", "Japanese", "Indoor"],
    indoor: true,
    ticketRequired: false,
    walkingDistance: "On Saadiyat Island",
    image: "/images/dining-default.jpg",
    whyChosen: "Elegant Japanese cuisine for a refined evening dining experience.",
    tips: ["Omakase menu for the full experience", "Sake pairing available"],
    lat: 24.5455,
    lng: 54.4310,
  },
  {
    id: "beirut-sur-mer",
    name: "Beirut Sur Mer",
    category: "dining",
    cuisine: "Lebanese",
    description: "A beloved Lebanese restaurant serving traditional meze, grilled meats, and fresh seafood with warm Arabian hospitality.",
    shortDescription: "Traditional Lebanese meze and grills with warm hospitality.",
    duration: "1.5 hrs",
    timeRange: "13:00 - 14:30",
    tags: ["Food", "Lebanese", "Indoor"],
    indoor: true,
    ticketRequired: false,
    walkingDistance: "On Saadiyat Island",
    image: "/images/dining-default.jpg",
    whyChosen: "Authentic Lebanese cuisine -- a staple of Gulf dining culture.",
    tips: ["The meze spread is incredible", "Save room for baklava"],
    lat: 24.5462,
    lng: 54.4322,
  },
  {
    id: "buddha-bar-beach",
    name: "Buddha-Bar Beach Abu Dhabi",
    category: "dining",
    cuisine: "Pacific Rim",
    description: "An iconic beachfront dining destination fusing Pacific Rim flavors with a lounge atmosphere. DJ sets, ocean views, and elevated Pan-Asian cuisine.",
    shortDescription: "Iconic beachfront lounge with Pacific Rim cuisine and DJ sets.",
    duration: "2 hrs",
    timeRange: "19:00 - 21:00",
    tags: ["Food", "Premium", "Outdoor"],
    indoor: false,
    ticketRequired: false,
    walkingDistance: "On the beachfront",
    image: "/images/dining-default.jpg",
    whyChosen: "A scene-setting dinner with global flavors and ocean views.",
    tips: ["Book a beachfront table at sunset", "Live DJ on weekends"],
    lat: 24.5473,
    lng: 54.4340,
  },
  {
    id: "erth-restaurant",
    name: "Erth Restaurant",
    category: "dining",
    cuisine: "Emirati",
    description: "Celebrating authentic Emirati cuisine, Erth serves traditional dishes like machboos, harees, and luqaimat in a contemporary setting that honors local heritage.",
    shortDescription: "Authentic Emirati cuisine celebrating local heritage and flavors.",
    duration: "1.5 hrs",
    timeRange: "13:00 - 14:30",
    tags: ["Food", "Emirati", "Indoor"],
    indoor: true,
    ticketRequired: false,
    walkingDistance: "On Saadiyat Island",
    image: "/images/dining-default.jpg",
    whyChosen: "A must for experiencing genuine Emirati flavors and hospitality.",
    tips: ["Try the machboos", "Luqaimat for dessert is a must", "Staff explain dishes beautifully"],
    lat: 24.5450,
    lng: 54.4305,
  },
  {
    id: "sal-saadiyat",
    name: "SAL Saadiyat Island",
    category: "dining",
    cuisine: "Mediterranean",
    description: "An upscale beachfront restaurant at the Jumeirah resort serving Mediterranean seafood, with feet-in-the-sand dining and a glamorous pool lounge.",
    shortDescription: "Upscale beachfront Mediterranean with feet-in-the-sand dining.",
    duration: "2 hrs",
    timeRange: "12:00 - 14:00",
    tags: ["Food", "Beach", "Premium"],
    indoor: false,
    ticketRequired: false,
    walkingDistance: "At Jumeirah Resort",
    image: "/images/dining-default.jpg",
    whyChosen: "Luxury beachside dining that combines great food with relaxation.",
    tips: ["Reserve a beachfront table", "Pool access included with dining"],
    lat: 24.5478,
    lng: 54.4345,
  },
  {
    id: "art-lounge-louvre",
    name: "Art Lounge Louvre Abu Dhabi",
    category: "dining",
    cuisine: "Japanese",
    description: "A sophisticated dining venue inside the Louvre complex offering Japanese-inspired cuisine amid art and architecture. A culinary experience as refined as the museum itself.",
    shortDescription: "Sophisticated Japanese-inspired dining inside the Louvre complex.",
    duration: "1.5 hrs",
    timeRange: "12:30 - 14:00",
    tags: ["Food", "Japanese", "Premium"],
    indoor: true,
    ticketRequired: false,
    walkingDistance: "Inside Louvre Abu Dhabi",
    image: "/images/louvre.jpg",
    whyChosen: "Dine surrounded by world-class art and architecture.",
    tips: ["Window seats overlook the water", "Tasting menu recommended"],
    lat: 24.5339,
    lng: 54.3984,
  },
  {
    id: "tean",
    name: "Tean",
    category: "dining",
    cuisine: "Arabic",
    description: "A modern Arabic restaurant celebrating Levantine and Gulf flavors with a contemporary twist. Beautiful open kitchen and terrace dining.",
    shortDescription: "Modern Arabic restaurant with Levantine and Gulf flavors.",
    duration: "1.5 hrs",
    timeRange: "19:30 - 21:00",
    tags: ["Food", "Arabic", "Indoor"],
    indoor: true,
    ticketRequired: false,
    walkingDistance: "On Saadiyat Island",
    image: "/images/dining-default.jpg",
    whyChosen: "Contemporary Arabic cuisine that blends tradition with innovation.",
    tips: ["The hummus is legendary", "Open kitchen is worth watching"],
    lat: 24.5458,
    lng: 54.4315,
  },
  {
    id: "black-tap",
    name: "Black Tap Saadiyat Island",
    category: "dining",
    cuisine: "Burgers",
    description: "The famous New York burger joint known for award-winning burgers and over-the-top CrazyShake milkshakes.",
    shortDescription: "Famous NYC burger joint with award-winning burgers and CrazyShakes.",
    duration: "1 hr",
    timeRange: "12:00 - 13:00",
    tags: ["Food", "Casual", "Indoor"],
    indoor: true,
    ticketRequired: false,
    walkingDistance: "At Mamsha Al Saadiyat",
    image: "/images/dining-default.jpg",
    whyChosen: "Quick, satisfying, and fun -- great for a casual lunch.",
    tips: ["The CrazyShakes are Instagram-worthy", "Come hungry"],
    lat: 24.5467,
    lng: 54.4316,
  },
  {
    id: "burro-blanco",
    name: "Burro Blanco",
    category: "dining",
    cuisine: "Mexican",
    description: "A lively Mexican cantina with authentic tacos, burritos, fresh guacamole, and margaritas in a colorful, casual setting.",
    shortDescription: "Lively Mexican cantina with authentic tacos and margaritas.",
    duration: "1 hr",
    timeRange: "13:00 - 14:00",
    tags: ["Food", "Mexican", "Casual"],
    indoor: true,
    ticketRequired: false,
    walkingDistance: "On Saadiyat Island",
    image: "/images/dining-default.jpg",
    whyChosen: "Fun and flavorful -- a great casual lunch option.",
    tips: ["The guacamole is made fresh", "Try the fish tacos"],
    lat: 24.5464,
    lng: 54.4312,
  },
  {
    id: "beach-house",
    name: "Beach House Abu Dhabi",
    category: "dining",
    cuisine: "Italian",
    description: "A relaxed Italian beachside restaurant at the Park Hyatt with ocean views, fresh pasta, and wood-fired specialties.",
    shortDescription: "Italian beachside dining at Park Hyatt with ocean views.",
    duration: "1.5 hrs",
    timeRange: "19:00 - 20:30",
    tags: ["Food", "Italian", "Beach"],
    indoor: false,
    ticketRequired: false,
    walkingDistance: "At Park Hyatt",
    image: "/images/park-hyatt.jpg",
    whyChosen: "Italian comfort food with your toes practically in the sand.",
    tips: ["Sunset tables are the best", "Fresh pasta made in-house"],
    lat: 24.5480,
    lng: 54.4348,
  },
]

// ─── BEACHES ────────────────────────────────────────────────────────────────
export const beaches: Experience[] = [
  {
    id: "mamsha-beach",
    name: "Mamsha Beach",
    category: "beach",
    description: "A pristine public beach along the Mamsha Al Saadiyat promenade with white sand, clear waters, and easy access to beachfront restaurants.",
    shortDescription: "Public white sand beach along the Mamsha promenade.",
    duration: "2 hrs",
    timeRange: "15:00 - 17:00",
    tags: ["Beach", "Outdoor", "Relaxed"],
    indoor: false,
    ticketRequired: false,
    walkingDistance: "At Mamsha Al Saadiyat",
    image: "/images/beach.jpg",
    whyChosen: "The most accessible beach with restaurants steps away.",
    tips: ["Free public access", "Sunscreen is essential", "Showers and facilities available"],
    lat: 24.5472,
    lng: 54.4330,
  },
  {
    id: "sal-beach",
    name: "SAL Beach",
    category: "beach",
    description: "An upscale private beach at the Jumeirah resort with luxury loungers, attentive service, and a Mediterranean restaurant on the sand.",
    shortDescription: "Luxury private beach at Jumeirah with premium service.",
    duration: "3 hrs",
    timeRange: "10:00 - 13:00",
    tags: ["Beach", "Premium", "Relaxed"],
    indoor: false,
    ticketRequired: true,
    walkingDistance: "At Jumeirah Resort",
    image: "/images/beach.jpg",
    whyChosen: "Premium beach experience with full service and dining.",
    tips: ["Day pass required", "Includes lounger and towel", "Order lunch from SAL restaurant"],
    lat: 24.5478,
    lng: 54.4345,
  },
  {
    id: "saadiyat-beach-club",
    name: "Saadiyat Beach Club",
    category: "beach",
    description: "An exclusive beach club with infinity pool, private beach, spa, and multiple dining options. The ultimate relaxation destination on the island.",
    shortDescription: "Exclusive beach club with infinity pool, spa, and private beach.",
    duration: "3 hrs",
    timeRange: "10:00 - 13:00",
    tags: ["Beach", "Premium", "Pool"],
    indoor: false,
    ticketRequired: true,
    walkingDistance: "Saadiyat Beach Club area",
    image: "/images/saadiyat-beach-club.jpg",
    whyChosen: "The ultimate beach day with pool, spa, and premium service.",
    tips: ["Book in advance on weekends", "Spa packages available", "Multiple restaurants on-site"],
    lat: 24.5465,
    lng: 54.4335,
  },
  {
    id: "kai-beach",
    name: "Kai Beach",
    category: "beach",
    description: "A serene and less-crowded beach stretch perfect for those seeking a quieter, more private seaside experience on Saadiyat Island.",
    shortDescription: "Serene, quieter beach for a more private seaside experience.",
    duration: "2 hrs",
    timeRange: "15:00 - 17:00",
    tags: ["Beach", "Outdoor", "Relaxed"],
    indoor: false,
    ticketRequired: false,
    walkingDistance: "On Saadiyat Island",
    image: "/images/kai-beach.jpg",
    whyChosen: "A peaceful escape from the busier beaches.",
    tips: ["Less crowded than Mamsha Beach", "Great for long walks", "Bring your own refreshments"],
    lat: 24.5460,
    lng: 54.4350,
  },
  {
    id: "saadiyat-beach-golf",
    name: "Saadiyat Beach Golf Club",
    category: "beach",
    description: "An 18-hole championship oceanfront golf course with stunning views, plus a clubhouse with dining and beach access.",
    shortDescription: "Championship oceanfront golf course with dining and beach access.",
    duration: "3 hrs",
    timeRange: "07:00 - 10:00",
    tags: ["Golf", "Outdoor", "Premium"],
    indoor: false,
    ticketRequired: true,
    walkingDistance: "Golf club area",
    image: "/images/beach.jpg",
    whyChosen: "For golfers, there's no better setting than an oceanfront course.",
    tips: ["Tee times book up quickly", "Clubhouse dining is open to non-golfers", "Early morning for cooler play"],
    lat: 24.5485,
    lng: 54.4355,
  },
]

// ─── HOTELS ─────────────────────────────────────────────────────────────────
export const hotels: Experience[] = [
  {
    id: "jumeirah-saadiyat",
    name: "Jumeirah at Saadiyat Island Resort",
    category: "hotel",
    description: "A luxurious beachfront resort with world-class spa, multiple restaurants, and direct beach access on one of Abu Dhabi's most pristine stretches of sand.",
    shortDescription: "Luxurious beachfront resort with spa and pristine beach access.",
    duration: "Overnight",
    timeRange: "Check-in 15:00",
    tags: ["Hotel", "Luxury", "Beach"],
    indoor: true,
    ticketRequired: false,
    walkingDistance: "Beachfront",
    image: "/images/park-hyatt.jpg",
    whyChosen: "The ideal base for exploring Saadiyat with beach and culture at your doorstep.",
    tips: ["Request an ocean-view room", "Spa is world-class", "Free shuttle to cultural district"],
    lat: 24.5476,
    lng: 54.4343,
  },
  {
    id: "park-hyatt",
    name: "Park Hyatt Abu Dhabi Hotel and Villas",
    category: "hotel",
    description: "An intimate luxury resort with private beach, world-class dining at Beach House, and serene villa accommodations surrounded by manicured gardens.",
    shortDescription: "Intimate luxury resort with private beach and villa accommodations.",
    duration: "Overnight",
    timeRange: "Check-in 15:00",
    tags: ["Hotel", "Luxury", "Beach"],
    indoor: true,
    ticketRequired: false,
    walkingDistance: "Beachfront",
    image: "/images/park-hyatt.jpg",
    whyChosen: "A peaceful retreat with exceptional dining and a private beach.",
    tips: ["The villas have private gardens", "Beach House restaurant is a highlight", "Excellent breakfast spread"],
    lat: 24.5482,
    lng: 54.4350,
  },
  {
    id: "rixos-premium",
    name: "Rixos Premium Saadiyat Island",
    category: "hotel",
    description: "A premium all-inclusive resort with ultra-luxurious amenities, extensive dining options, and a private beach stretching along the coast.",
    shortDescription: "Premium all-inclusive resort with extensive dining and private beach.",
    duration: "Overnight",
    timeRange: "Check-in 14:00",
    tags: ["Hotel", "All-Inclusive", "Beach"],
    indoor: true,
    ticketRequired: false,
    walkingDistance: "Beachfront",
    image: "/images/park-hyatt.jpg",
    whyChosen: "All-inclusive convenience so you can focus on enjoying the island.",
    tips: ["All-inclusive covers most dining", "Kids club available", "Multiple pools"],
    lat: 24.5488,
    lng: 54.4358,
  },
  {
    id: "saadiyat-rotana",
    name: "Saadiyat Rotana Resort and Villas",
    category: "hotel",
    description: "A family-friendly resort with spacious villas, multiple pools, and direct beach access, combining comfort with island living.",
    shortDescription: "Family-friendly resort with villas, pools, and beach access.",
    duration: "Overnight",
    timeRange: "Check-in 15:00",
    tags: ["Hotel", "Family", "Beach"],
    indoor: true,
    ticketRequired: false,
    walkingDistance: "Beachfront",
    image: "/images/park-hyatt.jpg",
    whyChosen: "Great value with family-friendly amenities and beach access.",
    tips: ["Villa accommodations are spacious", "Multiple dining options on-site", "Shuttle to cultural sites available"],
    lat: 24.5492,
    lng: 54.4362,
  },
  {
    id: "st-regis-saadiyat",
    name: "The St. Regis Saadiyat Island Resort",
    category: "hotel",
    description: "An ultra-luxury resort with butler service, a spectacular spa, championship golf access, and pristine beachfront dining.",
    shortDescription: "Ultra-luxury resort with butler service and championship golf access.",
    duration: "Overnight",
    timeRange: "Check-in 15:00",
    tags: ["Hotel", "Ultra-Luxury", "Beach"],
    indoor: true,
    ticketRequired: false,
    walkingDistance: "Beachfront",
    image: "/images/park-hyatt.jpg",
    whyChosen: "The pinnacle of luxury on Saadiyat with unparalleled service.",
    tips: ["Butler service in every room", "Iridium Spa is exceptional", "Golf club next door"],
    lat: 24.5495,
    lng: 54.4368,
  },
]

// ─── SHOPPING ───────────────────────────────────────────────────────────────
export const shopping: Experience[] = [
  {
    id: "saadiyat-grove",
    name: "The Collection at Saadiyat Grove",
    category: "shopping",
    description: "A contemporary lifestyle destination featuring boutique shopping, artisan cafes, and creative retail experiences set within Saadiyat Island's cultural district.",
    shortDescription: "Boutique shopping and artisan cafes in the cultural district.",
    duration: "1.5 hrs",
    timeRange: "16:00 - 17:30",
    tags: ["Shopping", "Food", "Outdoor"],
    indoor: false,
    ticketRequired: false,
    walkingDistance: "5 min from beach area",
    image: "/images/grove.jpg",
    whyChosen: "A relaxed way to wind down the day with shopping and local finds.",
    tips: ["Many shops accept international credit cards", "Look for local artisan products as souvenirs", "Several cafes offer vegan and gluten-free options"],
    lat: 24.538,
    lng: 54.421,
  },
]

// ─── COMBINED ALL EXPERIENCES ───────────────────────────────────────────────
export const allExperiences: Experience[] = [
  ...museums,
  ...coffeeShops,
  ...restaurants,
  ...beaches,
  ...hotels,
  ...shopping,
]

// ─── SAMPLE ITINERARIES (used for demo) ─────────────────────────────────────
export const mockItinerary: DayItinerary[] = [
  {
    day: 1,
    date: "Friday, March 14",
    experiences: [
      museums[0],          // Louvre Abu Dhabi
      coffeeShops[8],      // Museum Cafe Louvre
      restaurants[0],      // Fouquet's
      museums[2],          // Manarat Al Saadiyat
      beaches[0],          // Mamsha Beach
      restaurants[2],      // TOTO (dinner)
    ],
  },
  {
    day: 2,
    date: "Saturday, March 15",
    experiences: [
      coffeeShops[0],      // Mysk Bakery
      museums[1],          // Abrahamic Family House
      coffeeShops[11],     // MARA Cafe
      museums[5],          // Natural History Museum
      museums[3],          // teamLab Phenomena
      restaurants[6],      // Buddha-Bar Beach (dinner)
    ],
  },
]

export const paceOptions = [
  { id: "relaxed", label: "Relaxed", description: "Fewer activities, more breaks", icon: "leaf" },
  { id: "balanced", label: "Balanced", description: "Curated highlights", icon: "scale" },
  { id: "maximize", label: "Maximize", description: "Fit in as much as possible", icon: "zap" },
] as const

export const interestOptions = [
  { id: "art", label: "Art & Museums" },
  { id: "architecture", label: "Architecture" },
  { id: "food", label: "Food & Cafes" },
  { id: "nature", label: "Nature & Beach" },
  { id: "spiritual", label: "Spiritual / Reflection" },
  { id: "shopping", label: "Shopping" },
] as const

export const extraOptions = [
  { id: "exhibits", label: "Must-see specific exhibits" },
  { id: "dietary", label: "Dietary preferences" },
  { id: "low-walking", label: "Low walking preference" },
] as const
